version: '3'

services:

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  weather-service:
    build:
      context: ./../weather-service
      dockerfile: ./../weather-service/weather-service.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1    